apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: weather-service
  framework: spring

buildMetadata: [managedByLabel]

resources:
  - microservice-deployment.yaml
  - microservice-service.yaml

configMapGenerator:
  - name: database-configmap
    literals:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://weather-database:5432/weather
      - POSTGRES_HOST=weather-database
      - POSTGRES_DB=weather

secretGenerator:
  - name: database-secrets
    literals:
      - POSTGRES_USER=spring
      - SPRING_DATASOURCE_USERNAME=spring
      - POSTGRES_PASSWORD=1qay2wsx
      - SPRING_DATASOURCE_PASSWORD=1qay2wsx

