# App deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  # name of the pod created in deployment
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      # label to connect this deployment to the given service
      springbootweather: web
  template:
    metadata:
      labels:
        # label to connect this deployment to the given service
        springbootweather: web
      creationTimestamp: null
    spec:
      containers:
        # environment variables analog to docker-compose:
        - envFrom:
            - configMapRef:
                name: app-config
          # docker image used:
          image: springbootweather_app
          # The following line forces tilt to use the local image and not try to pull one from docker hub.
          imagePullPolicy: Never
          # name of container:
          name: app
          ports:
            # putting forward a container for localhost:
            - containerPort: 8080
              name: app-target-port
          resources: {}
      # sets a restart policy if app gets started before db is fully online:
      restartPolicy: Always
status: {}
