# This is a basic workflow to help you get started with Actions

name: CI-SPRING-BOOT

# Workflow will run, when new code is pushed to the repository
on: [push]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  # Uses the Dockerfile and docker-compose.yml to check if they are working and the application will be containerized.
  containerize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose -f "SpringBootWeather/docker-compose.yml" up -d --build

      - name: Check for container status
        run: docker-compose -f "SpringBootWeather/docker-compose.yml" ps

      - name: Stop containers
        run: docker-compose -f "SpringBootWeather/docker-compose.yml" down
